# Fichier de configuration du site à personnaliser
### Configuration minimale
site_name: Charl_Ine # Nom du site <70 caractères, apparait dans l'onglet du navigateur
site_url: https://i-charlys.github.io/Charl-Ine/ # Adresse web principale de publication du site, à modifier au format https://votre-pseudo-github.github.io/nom-depot/

### Configuration de métadonnées
# Métadonnées de description <300 caratères, et d'auteur pour toutes les pages du site 
site_description: Site web Charl_Ine, un site second cerveau sur la tech, l'economie et la science.
site_author: "i-charlys et kumo-h"

### Configuration du dépôt
# Ajoute en haut à droite de chaque page du site, icône, nom et lien vers le dépot GitHub du projet.
repo_url: https://github.com/i-charlys/Charl-Ine
repo_name: 'Charl_Ine' # Personnalise le nom générique "GitHub" donné par défaut au lien vers le dépot GitHub du projet.
# edit_uri: edit/main/docs/ # Complément au chemin pour aller depuis `repo_url:` jusqu'au répertoire `docs` ;
# Ce qui permet avec MkDocs-Material d'ajouter un bouton (crayon) d'édition du code source.md d'une page du site depuis le navigateur
# (edit => édition avec connexion | blob, tree => lecture anonyme)


### Configuration manuelle de la stucture de navigation
# Dossier source, chemin relatif au fichier mkdocs.yml
docs_dir: docs
# Structure du menu principal de navigation, chemins relatifs au dossier docs_dir
# nav: 
#   - La page d'accueil : index.md
#   # Référencer vos autres pages ci-dessus...

# Configuration du thème https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration
theme:
    name: 'material'
    # custom_dir: overrides #  
    font:
      text: Inter
      code: JetBrains Mono
    # logo: images/gem.svg
    favicon: images/obsidian-logo.png
    icon:
      logo: fontawesome/solid/gem
      repo: fontawesome/brands/github-alt

    palette: 
      - scheme: default
        primary: indigo
        accent: purple
        toggle:
          icon: material/weather-sunny
          name: Basculer en mode sombre
        toggle:
          icon: material/weather-sunny
          name: Basculer en mode sombre
      - scheme: slate
        accent: cyan
        toggle:
          icon: material/weather-night
          name: Basculer en mode clair

    features: 
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - toc.integrate
        - header.autohide
        - navigation.expand
        - search.suggest
        - search.highlight
        - search.share

markdown_extensions:
  - meta
  - def_list
  - attr_list
  - footnotes
  - admonition
  - toc:
        permalink: "&lozf;"
        toc_depth: 4
  - nl2br
  - mdx_breakless_lists
  - sane_lists
  - smarty
  - tables
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
        custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.keys:
        separator: "\uff0b"
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
        generic: true
        smart_dollar: false

plugins:
  - search
  - roamlinks 
  - mermaid2
  - callouts
  - git-revision-date-localized

  - obsidian-bridge:
      graph: true
  - macros

#  NAVIGATION AVEC PAGE GRAPH
nav:
  - Accueil: index.md
  - Graph: graph.md
  - Tech:
      - Tech: Tech/index.md
      - "L'intérêt d'un DNS chiffré": "Tech/L'intérêt d'un DNS chiffre.md"
      - "La Science Cachée de la Netteté en Jeu": Tech/nettete-en-jeu.md

copyright: >
    Second cerveau de <a href="https://github.com/i-Charlys" target="_blank">Charl-Ine</a> et de <a href="https://github.com/kumo-h" target="_blank">Charl-Ine</a>
    &copy; 2024 sous licence <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr" target="_blank">CC BY-NC-SA 4.0</a>


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/i-Charlys/
      name: Compte GitHub i-charlys
    - icon: fontawesome/brands/git
      link: https://github.com/kumo-h/
      name: Compte GitHub kumo-h

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/animations.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

extra_css:
  - stylesheets/extra.css
